//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18033
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radial.Tools.NhAuto.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Radial.Tools.NhAuto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 --参数@P0：Schema Name
        ///--参数@P1：Table Name
        ///DECLARE @schema_id int
        ///SELECT @schema_id=schema_id FROM sys.schemas WHERE name=@P0
        ///
        ///SELECT     
        ///a.name AS [Name],c.name AS [Type],a.length AS [Length],
        ///CASE WHEN EXISTS
        ///                           (SELECT     1
        ///                             FROM          sysobjects
        ///                             WHERE      xtype = &apos;PK&apos; AND parent_obj = a.id AND name IN
        ///                                                       (SELECT     name
        ///                                       [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SqlServerFieldDefinitionQuery {
            get {
                return ResourceManager.GetString("SqlServerFieldDefinitionQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT t.TABLE_SCHEMA [SchemaName],  t.TABLE_NAME [TableName] FROM INFORMATION_SCHEMA.TABLES t INNER JOIN  sys.schemas s ON t.TABLE_SCHEMA=s.name  WHERE
        ///t.TABLE_TYPE=&apos;BASE TABLE&apos; ORDER BY t.TABLE_TYPE, t.TABLE_NAME 的本地化字符串。
        /// </summary>
        internal static string SqlServerTablesQuery {
            get {
                return ResourceManager.GetString("SqlServerTablesQuery", resourceCulture);
            }
        }
    }
}
