//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
namespace Radial.Lock.Client.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ILockChannel : Radial.Lock.ILock, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class LockClient : System.ServiceModel.ClientBase<Radial.Lock.ILock>, Radial.Lock.ILock {
        
        public LockClient() {
        }
        
        public LockClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LockClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LockClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LockClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }

        public bool Acquire(string key, out Radial.Lock.LockObject obj)
        {
            return base.Channel.Acquire(key, out obj);
        }
        
        public void Release(string key) {
            base.Channel.Release(key);
        }
        
        public IList<Radial.Lock.LockObject> GetList() {
            return base.Channel.GetList();
        }
    }
}
